CREATE TABLE public.roles (
                              id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                              "name" varchar NOT NULL,
                              created_date timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                              updated_date timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                              "uuid" uuid NOT NULL,
                              CONSTRAINT roles_pk PRIMARY KEY (id),
                              CONSTRAINT roles_unique UNIQUE ("uuid")
);

CREATE TABLE public.roles_by_users (
                                       id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                       user_id int8 NOT NULL,
                                       role_id int8 NOT NULL,
                                       created_date timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                       updated_date timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                       "uuid" uuid NOT NULL,
                                       CONSTRAINT roles_by_users_pk PRIMARY KEY (id),
                                       CONSTRAINT roles_by_users_unique UNIQUE ("uuid"),
                                       CONSTRAINT roles_by_users_users_fk FOREIGN KEY (user_id) REFERENCES public.users(id),
                                       CONSTRAINT roles_by_users_roles_fk FOREIGN KEY (role_id) REFERENCES public.roles(id)
);

ALTER TABLE public.users ADD federal_state_id int8 NULL;
ALTER TABLE public.users ADD CONSTRAINT users_federal_state_fk FOREIGN KEY (federal_state_id) REFERENCES public.federal_states(id);